// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.26.1
// source: mstablemgr.proto

package mstablemgr

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 开台
type OpenTableReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TableId *int32 `protobuf:"varint,1,opt,name=table_id,json=tableId" json:"table_id,omitempty"`
	Wal     *bool  `protobuf:"varint,2,opt,name=wal" json:"wal,omitempty"`
}

func (x *OpenTableReq) Reset() {
	*x = OpenTableReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mstablemgr_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpenTableReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenTableReq) ProtoMessage() {}

func (x *OpenTableReq) ProtoReflect() protoreflect.Message {
	mi := &file_mstablemgr_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenTableReq.ProtoReflect.Descriptor instead.
func (*OpenTableReq) Descriptor() ([]byte, []int) {
	return file_mstablemgr_proto_rawDescGZIP(), []int{0}
}

func (x *OpenTableReq) GetTableId() int32 {
	if x != nil && x.TableId != nil {
		return *x.TableId
	}
	return 0
}

func (x *OpenTableReq) GetWal() bool {
	if x != nil && x.Wal != nil {
		return *x.Wal
	}
	return false
}

type OpenTableResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status *int32 `protobuf:"varint,1,opt,name=status" json:"status,omitempty"`
}

func (x *OpenTableResp) Reset() {
	*x = OpenTableResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mstablemgr_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpenTableResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenTableResp) ProtoMessage() {}

func (x *OpenTableResp) ProtoReflect() protoreflect.Message {
	mi := &file_mstablemgr_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenTableResp.ProtoReflect.Descriptor instead.
func (*OpenTableResp) Descriptor() ([]byte, []int) {
	return file_mstablemgr_proto_rawDescGZIP(), []int{1}
}

func (x *OpenTableResp) GetStatus() int32 {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return 0
}

// 换台
type ChangeTableReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ChangeTableReq) Reset() {
	*x = ChangeTableReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mstablemgr_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeTableReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeTableReq) ProtoMessage() {}

func (x *ChangeTableReq) ProtoReflect() protoreflect.Message {
	mi := &file_mstablemgr_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeTableReq.ProtoReflect.Descriptor instead.
func (*ChangeTableReq) Descriptor() ([]byte, []int) {
	return file_mstablemgr_proto_rawDescGZIP(), []int{2}
}

type ChangeTableResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ChangeTableResp) Reset() {
	*x = ChangeTableResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mstablemgr_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeTableResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeTableResp) ProtoMessage() {}

func (x *ChangeTableResp) ProtoReflect() protoreflect.Message {
	mi := &file_mstablemgr_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeTableResp.ProtoReflect.Descriptor instead.
func (*ChangeTableResp) Descriptor() ([]byte, []int) {
	return file_mstablemgr_proto_rawDescGZIP(), []int{3}
}

// 结台
type CompleteTableReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TableId *int32 `protobuf:"varint,1,opt,name=table_id,json=tableId" json:"table_id,omitempty"`
	Wal     *bool  `protobuf:"varint,2,opt,name=wal" json:"wal,omitempty"`
}

func (x *CompleteTableReq) Reset() {
	*x = CompleteTableReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mstablemgr_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompleteTableReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteTableReq) ProtoMessage() {}

func (x *CompleteTableReq) ProtoReflect() protoreflect.Message {
	mi := &file_mstablemgr_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteTableReq.ProtoReflect.Descriptor instead.
func (*CompleteTableReq) Descriptor() ([]byte, []int) {
	return file_mstablemgr_proto_rawDescGZIP(), []int{4}
}

func (x *CompleteTableReq) GetTableId() int32 {
	if x != nil && x.TableId != nil {
		return *x.TableId
	}
	return 0
}

func (x *CompleteTableReq) GetWal() bool {
	if x != nil && x.Wal != nil {
		return *x.Wal
	}
	return false
}

type CompleteTableResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status *int32 `protobuf:"varint,1,opt,name=status" json:"status,omitempty"`
}

func (x *CompleteTableResp) Reset() {
	*x = CompleteTableResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mstablemgr_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompleteTableResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteTableResp) ProtoMessage() {}

func (x *CompleteTableResp) ProtoReflect() protoreflect.Message {
	mi := &file_mstablemgr_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteTableResp.ProtoReflect.Descriptor instead.
func (*CompleteTableResp) Descriptor() ([]byte, []int) {
	return file_mstablemgr_proto_rawDescGZIP(), []int{5}
}

func (x *CompleteTableResp) GetStatus() int32 {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return 0
}

// 获取点菜详情
type GetOrderDetailReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetOrderDetailReq) Reset() {
	*x = GetOrderDetailReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mstablemgr_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOrderDetailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderDetailReq) ProtoMessage() {}

func (x *GetOrderDetailReq) ProtoReflect() protoreflect.Message {
	mi := &file_mstablemgr_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderDetailReq.ProtoReflect.Descriptor instead.
func (*GetOrderDetailReq) Descriptor() ([]byte, []int) {
	return file_mstablemgr_proto_rawDescGZIP(), []int{6}
}

type GetOrderDetailResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetOrderDetailResp) Reset() {
	*x = GetOrderDetailResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mstablemgr_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOrderDetailResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderDetailResp) ProtoMessage() {}

func (x *GetOrderDetailResp) ProtoReflect() protoreflect.Message {
	mi := &file_mstablemgr_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderDetailResp.ProtoReflect.Descriptor instead.
func (*GetOrderDetailResp) Descriptor() ([]byte, []int) {
	return file_mstablemgr_proto_rawDescGZIP(), []int{7}
}

// 加台
type AddTableReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AddTableReq) Reset() {
	*x = AddTableReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mstablemgr_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddTableReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTableReq) ProtoMessage() {}

func (x *AddTableReq) ProtoReflect() protoreflect.Message {
	mi := &file_mstablemgr_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTableReq.ProtoReflect.Descriptor instead.
func (*AddTableReq) Descriptor() ([]byte, []int) {
	return file_mstablemgr_proto_rawDescGZIP(), []int{8}
}

type AddTableResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AddTableResp) Reset() {
	*x = AddTableResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mstablemgr_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddTableResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTableResp) ProtoMessage() {}

func (x *AddTableResp) ProtoReflect() protoreflect.Message {
	mi := &file_mstablemgr_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTableResp.ProtoReflect.Descriptor instead.
func (*AddTableResp) Descriptor() ([]byte, []int) {
	return file_mstablemgr_proto_rawDescGZIP(), []int{9}
}

// 减台
type DelTableReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DelTableReq) Reset() {
	*x = DelTableReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mstablemgr_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelTableReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelTableReq) ProtoMessage() {}

func (x *DelTableReq) ProtoReflect() protoreflect.Message {
	mi := &file_mstablemgr_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelTableReq.ProtoReflect.Descriptor instead.
func (*DelTableReq) Descriptor() ([]byte, []int) {
	return file_mstablemgr_proto_rawDescGZIP(), []int{10}
}

type DelTableResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DelTableResp) Reset() {
	*x = DelTableResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mstablemgr_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelTableResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelTableResp) ProtoMessage() {}

func (x *DelTableResp) ProtoReflect() protoreflect.Message {
	mi := &file_mstablemgr_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelTableResp.ProtoReflect.Descriptor instead.
func (*DelTableResp) Descriptor() ([]byte, []int) {
	return file_mstablemgr_proto_rawDescGZIP(), []int{11}
}

type GetTablesStatusReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetTablesStatusReq) Reset() {
	*x = GetTablesStatusReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mstablemgr_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTablesStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTablesStatusReq) ProtoMessage() {}

func (x *GetTablesStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_mstablemgr_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTablesStatusReq.ProtoReflect.Descriptor instead.
func (*GetTablesStatusReq) Descriptor() ([]byte, []int) {
	return file_mstablemgr_proto_rawDescGZIP(), []int{12}
}

type TableInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TableId *int32 `protobuf:"varint,1,opt,name=table_id,json=tableId" json:"table_id,omitempty"`
	Status  *int32 `protobuf:"varint,2,opt,name=status" json:"status,omitempty"`
}

func (x *TableInfo) Reset() {
	*x = TableInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mstablemgr_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TableInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableInfo) ProtoMessage() {}

func (x *TableInfo) ProtoReflect() protoreflect.Message {
	mi := &file_mstablemgr_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableInfo.ProtoReflect.Descriptor instead.
func (*TableInfo) Descriptor() ([]byte, []int) {
	return file_mstablemgr_proto_rawDescGZIP(), []int{13}
}

func (x *TableInfo) GetTableId() int32 {
	if x != nil && x.TableId != nil {
		return *x.TableId
	}
	return 0
}

func (x *TableInfo) GetStatus() int32 {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return 0
}

type GetTablesStatusResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TableList []*TableInfo `protobuf:"bytes,1,rep,name=table_list,json=tableList" json:"table_list,omitempty"`
}

func (x *GetTablesStatusResp) Reset() {
	*x = GetTablesStatusResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mstablemgr_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTablesStatusResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTablesStatusResp) ProtoMessage() {}

func (x *GetTablesStatusResp) ProtoReflect() protoreflect.Message {
	mi := &file_mstablemgr_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTablesStatusResp.ProtoReflect.Descriptor instead.
func (*GetTablesStatusResp) Descriptor() ([]byte, []int) {
	return file_mstablemgr_proto_rawDescGZIP(), []int{14}
}

func (x *GetTablesStatusResp) GetTableList() []*TableInfo {
	if x != nil {
		return x.TableList
	}
	return nil
}

var File_mstablemgr_proto protoreflect.FileDescriptor

var file_mstablemgr_proto_rawDesc = []byte{
	0x0a, 0x10, 0x6d, 0x73, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x6d, 0x67, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0a, 0x6d, 0x73, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x6d, 0x67, 0x72, 0x22, 0x3b,
	0x0a, 0x0c, 0x4f, 0x70, 0x65, 0x6e, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x12, 0x19,
	0x0a, 0x08, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x07, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x77, 0x61, 0x6c,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x03, 0x77, 0x61, 0x6c, 0x22, 0x27, 0x0a, 0x0d, 0x4f,
	0x70, 0x65, 0x6e, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x22, 0x10, 0x0a, 0x0e, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x54, 0x61,
	0x62, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x22, 0x11, 0x0a, 0x0f, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65,
	0x54, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x22, 0x3f, 0x0a, 0x10, 0x43, 0x6f, 0x6d,
	0x70, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x12, 0x19, 0x0a,
	0x08, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x07, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x77, 0x61, 0x6c, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x03, 0x77, 0x61, 0x6c, 0x22, 0x2b, 0x0a, 0x11, 0x43, 0x6f,
	0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x13, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x22, 0x14, 0x0a, 0x12,
	0x47, 0x65, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65,
	0x73, 0x70, 0x22, 0x0d, 0x0a, 0x0b, 0x41, 0x64, 0x64, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65,
	0x71, 0x22, 0x0e, 0x0a, 0x0c, 0x41, 0x64, 0x64, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x22, 0x0d, 0x0a, 0x0b, 0x44, 0x65, 0x6c, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x71,
	0x22, 0x0e, 0x0a, 0x0c, 0x44, 0x65, 0x6c, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x22, 0x14, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x22, 0x3e, 0x0a, 0x09, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x4b, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x54, 0x61, 0x62,
	0x6c, 0x65, 0x73, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x34, 0x0a,
	0x0a, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x15, 0x2e, 0x6d, 0x73, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x6d, 0x67, 0x72, 0x2e, 0x54,
	0x61, 0x62, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x09, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x4c,
	0x69, 0x73, 0x74, 0x32, 0x87, 0x04, 0x0a, 0x0a, 0x4d, 0x53, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x4d,
	0x67, 0x72, 0x12, 0x40, 0x0a, 0x09, 0x4f, 0x70, 0x65, 0x6e, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x12,
	0x18, 0x2e, 0x6d, 0x73, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x6d, 0x67, 0x72, 0x2e, 0x4f, 0x70, 0x65,
	0x6e, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x19, 0x2e, 0x6d, 0x73, 0x74, 0x61,
	0x62, 0x6c, 0x65, 0x6d, 0x67, 0x72, 0x2e, 0x4f, 0x70, 0x65, 0x6e, 0x54, 0x61, 0x62, 0x6c, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x46, 0x0a, 0x0b, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x54, 0x61,
	0x62, 0x6c, 0x65, 0x12, 0x1a, 0x2e, 0x6d, 0x73, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x6d, 0x67, 0x72,
	0x2e, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x1a,
	0x1b, 0x2e, 0x6d, 0x73, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x6d, 0x67, 0x72, 0x2e, 0x43, 0x68, 0x61,
	0x6e, 0x67, 0x65, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x4c, 0x0a, 0x0d,
	0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x1c, 0x2e,
	0x6d, 0x73, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x6d, 0x67, 0x72, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x6c,
	0x65, 0x74, 0x65, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x1d, 0x2e, 0x6d, 0x73,
	0x74, 0x61, 0x62, 0x6c, 0x65, 0x6d, 0x67, 0x72, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74,
	0x65, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x4f, 0x0a, 0x0e, 0x47, 0x65,
	0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x1d, 0x2e, 0x6d,
	0x73, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x6d, 0x67, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x1a, 0x1e, 0x2e, 0x6d, 0x73,
	0x74, 0x61, 0x62, 0x6c, 0x65, 0x6d, 0x67, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x12, 0x3d, 0x0a, 0x08, 0x41,
	0x64, 0x64, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x17, 0x2e, 0x6d, 0x73, 0x74, 0x61, 0x62, 0x6c,
	0x65, 0x6d, 0x67, 0x72, 0x2e, 0x41, 0x64, 0x64, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x71,
	0x1a, 0x18, 0x2e, 0x6d, 0x73, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x6d, 0x67, 0x72, 0x2e, 0x41, 0x64,
	0x64, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x3d, 0x0a, 0x08, 0x44, 0x65,
	0x6c, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x17, 0x2e, 0x6d, 0x73, 0x74, 0x61, 0x62, 0x6c, 0x65,
	0x6d, 0x67, 0x72, 0x2e, 0x44, 0x65, 0x6c, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x1a,
	0x18, 0x2e, 0x6d, 0x73, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x6d, 0x67, 0x72, 0x2e, 0x44, 0x65, 0x6c,
	0x54, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x52, 0x0a, 0x0f, 0x47, 0x65, 0x74,
	0x54, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1e, 0x2e, 0x6d,
	0x73, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x6d, 0x67, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x61, 0x62,
	0x6c, 0x65, 0x73, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x1f, 0x2e, 0x6d,
	0x73, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x6d, 0x67, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x61, 0x62,
	0x6c, 0x65, 0x73, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x42, 0x0e, 0x5a,
	0x0c, 0x2e, 0x3b, 0x6d, 0x73, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x6d, 0x67, 0x72,
}

var (
	file_mstablemgr_proto_rawDescOnce sync.Once
	file_mstablemgr_proto_rawDescData = file_mstablemgr_proto_rawDesc
)

func file_mstablemgr_proto_rawDescGZIP() []byte {
	file_mstablemgr_proto_rawDescOnce.Do(func() {
		file_mstablemgr_proto_rawDescData = protoimpl.X.CompressGZIP(file_mstablemgr_proto_rawDescData)
	})
	return file_mstablemgr_proto_rawDescData
}

var file_mstablemgr_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_mstablemgr_proto_goTypes = []interface{}{
	(*OpenTableReq)(nil),        // 0: mstablemgr.OpenTableReq
	(*OpenTableResp)(nil),       // 1: mstablemgr.OpenTableResp
	(*ChangeTableReq)(nil),      // 2: mstablemgr.ChangeTableReq
	(*ChangeTableResp)(nil),     // 3: mstablemgr.ChangeTableResp
	(*CompleteTableReq)(nil),    // 4: mstablemgr.CompleteTableReq
	(*CompleteTableResp)(nil),   // 5: mstablemgr.CompleteTableResp
	(*GetOrderDetailReq)(nil),   // 6: mstablemgr.GetOrderDetailReq
	(*GetOrderDetailResp)(nil),  // 7: mstablemgr.GetOrderDetailResp
	(*AddTableReq)(nil),         // 8: mstablemgr.AddTableReq
	(*AddTableResp)(nil),        // 9: mstablemgr.AddTableResp
	(*DelTableReq)(nil),         // 10: mstablemgr.DelTableReq
	(*DelTableResp)(nil),        // 11: mstablemgr.DelTableResp
	(*GetTablesStatusReq)(nil),  // 12: mstablemgr.GetTablesStatusReq
	(*TableInfo)(nil),           // 13: mstablemgr.TableInfo
	(*GetTablesStatusResp)(nil), // 14: mstablemgr.GetTablesStatusResp
}
var file_mstablemgr_proto_depIdxs = []int32{
	13, // 0: mstablemgr.GetTablesStatusResp.table_list:type_name -> mstablemgr.TableInfo
	0,  // 1: mstablemgr.MSTableMgr.OpenTable:input_type -> mstablemgr.OpenTableReq
	2,  // 2: mstablemgr.MSTableMgr.ChangeTable:input_type -> mstablemgr.ChangeTableReq
	4,  // 3: mstablemgr.MSTableMgr.CompleteTable:input_type -> mstablemgr.CompleteTableReq
	6,  // 4: mstablemgr.MSTableMgr.GetOrderDetail:input_type -> mstablemgr.GetOrderDetailReq
	8,  // 5: mstablemgr.MSTableMgr.AddTable:input_type -> mstablemgr.AddTableReq
	10, // 6: mstablemgr.MSTableMgr.DelTable:input_type -> mstablemgr.DelTableReq
	12, // 7: mstablemgr.MSTableMgr.GetTablesStatus:input_type -> mstablemgr.GetTablesStatusReq
	1,  // 8: mstablemgr.MSTableMgr.OpenTable:output_type -> mstablemgr.OpenTableResp
	3,  // 9: mstablemgr.MSTableMgr.ChangeTable:output_type -> mstablemgr.ChangeTableResp
	5,  // 10: mstablemgr.MSTableMgr.CompleteTable:output_type -> mstablemgr.CompleteTableResp
	7,  // 11: mstablemgr.MSTableMgr.GetOrderDetail:output_type -> mstablemgr.GetOrderDetailResp
	9,  // 12: mstablemgr.MSTableMgr.AddTable:output_type -> mstablemgr.AddTableResp
	11, // 13: mstablemgr.MSTableMgr.DelTable:output_type -> mstablemgr.DelTableResp
	14, // 14: mstablemgr.MSTableMgr.GetTablesStatus:output_type -> mstablemgr.GetTablesStatusResp
	8,  // [8:15] is the sub-list for method output_type
	1,  // [1:8] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_mstablemgr_proto_init() }
func file_mstablemgr_proto_init() {
	if File_mstablemgr_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_mstablemgr_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OpenTableReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mstablemgr_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OpenTableResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mstablemgr_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangeTableReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mstablemgr_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangeTableResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mstablemgr_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CompleteTableReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mstablemgr_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CompleteTableResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mstablemgr_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOrderDetailReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mstablemgr_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOrderDetailResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mstablemgr_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddTableReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mstablemgr_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddTableResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mstablemgr_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelTableReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mstablemgr_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelTableResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mstablemgr_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTablesStatusReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mstablemgr_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TableInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mstablemgr_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTablesStatusResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mstablemgr_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mstablemgr_proto_goTypes,
		DependencyIndexes: file_mstablemgr_proto_depIdxs,
		MessageInfos:      file_mstablemgr_proto_msgTypes,
	}.Build()
	File_mstablemgr_proto = out.File
	file_mstablemgr_proto_rawDesc = nil
	file_mstablemgr_proto_goTypes = nil
	file_mstablemgr_proto_depIdxs = nil
}
