// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: msdbcall.proto

package msdbcall

import (
	proto "db_proj/model/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateUserReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User *proto.User `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
}

func (x *CreateUserReq) Reset() {
	*x = CreateUserReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msdbcall_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserReq) ProtoMessage() {}

func (x *CreateUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_msdbcall_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserReq.ProtoReflect.Descriptor instead.
func (*CreateUserReq) Descriptor() ([]byte, []int) {
	return file_msdbcall_proto_rawDescGZIP(), []int{0}
}

func (x *CreateUserReq) GetUser() *proto.User {
	if x != nil {
		return x.User
	}
	return nil
}

type CreateUserResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *string `protobuf:"bytes,1,opt,name=data" json:"data,omitempty"` // 返回新插入的user的json
	Code *int32  `protobuf:"varint,2,opt,name=code" json:"code,omitempty"`
}

func (x *CreateUserResp) Reset() {
	*x = CreateUserResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msdbcall_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateUserResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserResp) ProtoMessage() {}

func (x *CreateUserResp) ProtoReflect() protoreflect.Message {
	mi := &file_msdbcall_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserResp.ProtoReflect.Descriptor instead.
func (*CreateUserResp) Descriptor() ([]byte, []int) {
	return file_msdbcall_proto_rawDescGZIP(), []int{1}
}

func (x *CreateUserResp) GetData() string {
	if x != nil && x.Data != nil {
		return *x.Data
	}
	return ""
}

func (x *CreateUserResp) GetCode() int32 {
	if x != nil && x.Code != nil {
		return *x.Code
	}
	return 0
}

type AddDishReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dish *proto.Dish `protobuf:"bytes,1,opt,name=dish" json:"dish,omitempty"`
}

func (x *AddDishReq) Reset() {
	*x = AddDishReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msdbcall_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddDishReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddDishReq) ProtoMessage() {}

func (x *AddDishReq) ProtoReflect() protoreflect.Message {
	mi := &file_msdbcall_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddDishReq.ProtoReflect.Descriptor instead.
func (*AddDishReq) Descriptor() ([]byte, []int) {
	return file_msdbcall_proto_rawDescGZIP(), []int{2}
}

func (x *AddDishReq) GetDish() *proto.Dish {
	if x != nil {
		return x.Dish
	}
	return nil
}

type AddDishResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *string `protobuf:"bytes,1,opt,name=data" json:"data,omitempty"`
}

func (x *AddDishResp) Reset() {
	*x = AddDishResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msdbcall_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddDishResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddDishResp) ProtoMessage() {}

func (x *AddDishResp) ProtoReflect() protoreflect.Message {
	mi := &file_msdbcall_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddDishResp.ProtoReflect.Descriptor instead.
func (*AddDishResp) Descriptor() ([]byte, []int) {
	return file_msdbcall_proto_rawDescGZIP(), []int{3}
}

func (x *AddDishResp) GetData() string {
	if x != nil && x.Data != nil {
		return *x.Data
	}
	return ""
}

type CheckUserPasswordReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 三选一，都有的话优先级为 uin > phone > email
	Uin         *string `protobuf:"bytes,1,opt,name=uin" json:"uin,omitempty"`
	PhoneNumber *string `protobuf:"bytes,2,opt,name=phone_number,json=phoneNumber" json:"phone_number,omitempty"`
	Email       *string `protobuf:"bytes,3,opt,name=email" json:"email,omitempty"`
	Password    *string `protobuf:"bytes,4,opt,name=password" json:"password,omitempty"`
}

func (x *CheckUserPasswordReq) Reset() {
	*x = CheckUserPasswordReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msdbcall_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckUserPasswordReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckUserPasswordReq) ProtoMessage() {}

func (x *CheckUserPasswordReq) ProtoReflect() protoreflect.Message {
	mi := &file_msdbcall_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckUserPasswordReq.ProtoReflect.Descriptor instead.
func (*CheckUserPasswordReq) Descriptor() ([]byte, []int) {
	return file_msdbcall_proto_rawDescGZIP(), []int{4}
}

func (x *CheckUserPasswordReq) GetUin() string {
	if x != nil && x.Uin != nil {
		return *x.Uin
	}
	return ""
}

func (x *CheckUserPasswordReq) GetPhoneNumber() string {
	if x != nil && x.PhoneNumber != nil {
		return *x.PhoneNumber
	}
	return ""
}

func (x *CheckUserPasswordReq) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

func (x *CheckUserPasswordReq) GetPassword() string {
	if x != nil && x.Password != nil {
		return *x.Password
	}
	return ""
}

type CheckUserPasswordResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status *int32 `protobuf:"varint,1,opt,name=status" json:"status,omitempty"`
}

func (x *CheckUserPasswordResp) Reset() {
	*x = CheckUserPasswordResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msdbcall_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckUserPasswordResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckUserPasswordResp) ProtoMessage() {}

func (x *CheckUserPasswordResp) ProtoReflect() protoreflect.Message {
	mi := &file_msdbcall_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckUserPasswordResp.ProtoReflect.Descriptor instead.
func (*CheckUserPasswordResp) Descriptor() ([]byte, []int) {
	return file_msdbcall_proto_rawDescGZIP(), []int{5}
}

func (x *CheckUserPasswordResp) GetStatus() int32 {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return 0
}

type GetUserInfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uin         *string `protobuf:"bytes,1,opt,name=uin" json:"uin,omitempty"`
	PhoneNumber *string `protobuf:"bytes,2,opt,name=phone_number,json=phoneNumber" json:"phone_number,omitempty"`
	Email       *string `protobuf:"bytes,3,opt,name=email" json:"email,omitempty"`
}

func (x *GetUserInfoReq) Reset() {
	*x = GetUserInfoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msdbcall_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoReq) ProtoMessage() {}

func (x *GetUserInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_msdbcall_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoReq.ProtoReflect.Descriptor instead.
func (*GetUserInfoReq) Descriptor() ([]byte, []int) {
	return file_msdbcall_proto_rawDescGZIP(), []int{6}
}

func (x *GetUserInfoReq) GetUin() string {
	if x != nil && x.Uin != nil {
		return *x.Uin
	}
	return ""
}

func (x *GetUserInfoReq) GetPhoneNumber() string {
	if x != nil && x.PhoneNumber != nil {
		return *x.PhoneNumber
	}
	return ""
}

func (x *GetUserInfoReq) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

type GetUserInfoResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status *int32  `protobuf:"varint,1,opt,name=status" json:"status,omitempty"`
	Data   *string `protobuf:"bytes,2,opt,name=data" json:"data,omitempty"`
}

func (x *GetUserInfoResp) Reset() {
	*x = GetUserInfoResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msdbcall_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoResp) ProtoMessage() {}

func (x *GetUserInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_msdbcall_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoResp.ProtoReflect.Descriptor instead.
func (*GetUserInfoResp) Descriptor() ([]byte, []int) {
	return file_msdbcall_proto_rawDescGZIP(), []int{7}
}

func (x *GetUserInfoResp) GetStatus() int32 {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return 0
}

func (x *GetUserInfoResp) GetData() string {
	if x != nil && x.Data != nil {
		return *x.Data
	}
	return ""
}

type ModifyPasswordReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 三选一，都有的话优先级为 uin > phone > email
	Uin         *string `protobuf:"bytes,1,opt,name=uin" json:"uin,omitempty"`
	PhoneNumber *string `protobuf:"bytes,2,opt,name=phone_number,json=phoneNumber" json:"phone_number,omitempty"`
	Email       *string `protobuf:"bytes,3,opt,name=email" json:"email,omitempty"`
	OldPassword *string `protobuf:"bytes,4,opt,name=old_password,json=oldPassword" json:"old_password,omitempty"`
	NewPassword *string `protobuf:"bytes,5,opt,name=new_password,json=newPassword" json:"new_password,omitempty"`
}

func (x *ModifyPasswordReq) Reset() {
	*x = ModifyPasswordReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msdbcall_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModifyPasswordReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifyPasswordReq) ProtoMessage() {}

func (x *ModifyPasswordReq) ProtoReflect() protoreflect.Message {
	mi := &file_msdbcall_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifyPasswordReq.ProtoReflect.Descriptor instead.
func (*ModifyPasswordReq) Descriptor() ([]byte, []int) {
	return file_msdbcall_proto_rawDescGZIP(), []int{8}
}

func (x *ModifyPasswordReq) GetUin() string {
	if x != nil && x.Uin != nil {
		return *x.Uin
	}
	return ""
}

func (x *ModifyPasswordReq) GetPhoneNumber() string {
	if x != nil && x.PhoneNumber != nil {
		return *x.PhoneNumber
	}
	return ""
}

func (x *ModifyPasswordReq) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

func (x *ModifyPasswordReq) GetOldPassword() string {
	if x != nil && x.OldPassword != nil {
		return *x.OldPassword
	}
	return ""
}

func (x *ModifyPasswordReq) GetNewPassword() string {
	if x != nil && x.NewPassword != nil {
		return *x.NewPassword
	}
	return ""
}

type ModifyPasswordResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status *int32 `protobuf:"varint,1,opt,name=status" json:"status,omitempty"`
}

func (x *ModifyPasswordResp) Reset() {
	*x = ModifyPasswordResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msdbcall_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModifyPasswordResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifyPasswordResp) ProtoMessage() {}

func (x *ModifyPasswordResp) ProtoReflect() protoreflect.Message {
	mi := &file_msdbcall_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifyPasswordResp.ProtoReflect.Descriptor instead.
func (*ModifyPasswordResp) Descriptor() ([]byte, []int) {
	return file_msdbcall_proto_rawDescGZIP(), []int{9}
}

func (x *ModifyPasswordResp) GetStatus() int32 {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return 0
}

type CheckUserPhoneUniqueReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PhoneNumber *string `protobuf:"bytes,1,opt,name=phone_number,json=phoneNumber" json:"phone_number,omitempty"`
}

func (x *CheckUserPhoneUniqueReq) Reset() {
	*x = CheckUserPhoneUniqueReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msdbcall_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckUserPhoneUniqueReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckUserPhoneUniqueReq) ProtoMessage() {}

func (x *CheckUserPhoneUniqueReq) ProtoReflect() protoreflect.Message {
	mi := &file_msdbcall_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckUserPhoneUniqueReq.ProtoReflect.Descriptor instead.
func (*CheckUserPhoneUniqueReq) Descriptor() ([]byte, []int) {
	return file_msdbcall_proto_rawDescGZIP(), []int{10}
}

func (x *CheckUserPhoneUniqueReq) GetPhoneNumber() string {
	if x != nil && x.PhoneNumber != nil {
		return *x.PhoneNumber
	}
	return ""
}

type CheckUserPhoneUniqueResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Unique *bool `protobuf:"varint,1,opt,name=unique" json:"unique,omitempty"`
}

func (x *CheckUserPhoneUniqueResp) Reset() {
	*x = CheckUserPhoneUniqueResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msdbcall_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckUserPhoneUniqueResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckUserPhoneUniqueResp) ProtoMessage() {}

func (x *CheckUserPhoneUniqueResp) ProtoReflect() protoreflect.Message {
	mi := &file_msdbcall_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckUserPhoneUniqueResp.ProtoReflect.Descriptor instead.
func (*CheckUserPhoneUniqueResp) Descriptor() ([]byte, []int) {
	return file_msdbcall_proto_rawDescGZIP(), []int{11}
}

func (x *CheckUserPhoneUniqueResp) GetUnique() bool {
	if x != nil && x.Unique != nil {
		return *x.Unique
	}
	return false
}

type CheckUserEmailUniqueReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email *string `protobuf:"bytes,1,opt,name=email" json:"email,omitempty"`
}

func (x *CheckUserEmailUniqueReq) Reset() {
	*x = CheckUserEmailUniqueReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msdbcall_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckUserEmailUniqueReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckUserEmailUniqueReq) ProtoMessage() {}

func (x *CheckUserEmailUniqueReq) ProtoReflect() protoreflect.Message {
	mi := &file_msdbcall_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckUserEmailUniqueReq.ProtoReflect.Descriptor instead.
func (*CheckUserEmailUniqueReq) Descriptor() ([]byte, []int) {
	return file_msdbcall_proto_rawDescGZIP(), []int{12}
}

func (x *CheckUserEmailUniqueReq) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

type CheckUserEmailUniqueResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Unique *bool `protobuf:"varint,1,opt,name=unique" json:"unique,omitempty"`
}

func (x *CheckUserEmailUniqueResp) Reset() {
	*x = CheckUserEmailUniqueResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msdbcall_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckUserEmailUniqueResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckUserEmailUniqueResp) ProtoMessage() {}

func (x *CheckUserEmailUniqueResp) ProtoReflect() protoreflect.Message {
	mi := &file_msdbcall_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckUserEmailUniqueResp.ProtoReflect.Descriptor instead.
func (*CheckUserEmailUniqueResp) Descriptor() ([]byte, []int) {
	return file_msdbcall_proto_rawDescGZIP(), []int{13}
}

func (x *CheckUserEmailUniqueResp) GetUnique() bool {
	if x != nil && x.Unique != nil {
		return *x.Unique
	}
	return false
}

type GetDishListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetDishListReq) Reset() {
	*x = GetDishListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msdbcall_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDishListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDishListReq) ProtoMessage() {}

func (x *GetDishListReq) ProtoReflect() protoreflect.Message {
	mi := &file_msdbcall_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDishListReq.ProtoReflect.Descriptor instead.
func (*GetDishListReq) Descriptor() ([]byte, []int) {
	return file_msdbcall_proto_rawDescGZIP(), []int{14}
}

type GetDishListResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DishList []*proto.Dish `protobuf:"bytes,1,rep,name=dish_list,json=dishList" json:"dish_list,omitempty"`
}

func (x *GetDishListResp) Reset() {
	*x = GetDishListResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msdbcall_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDishListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDishListResp) ProtoMessage() {}

func (x *GetDishListResp) ProtoReflect() protoreflect.Message {
	mi := &file_msdbcall_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDishListResp.ProtoReflect.Descriptor instead.
func (*GetDishListResp) Descriptor() ([]byte, []int) {
	return file_msdbcall_proto_rawDescGZIP(), []int{15}
}

func (x *GetDishListResp) GetDishList() []*proto.Dish {
	if x != nil {
		return x.DishList
	}
	return nil
}

type DeleteDishReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id *int32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (x *DeleteDishReq) Reset() {
	*x = DeleteDishReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msdbcall_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteDishReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDishReq) ProtoMessage() {}

func (x *DeleteDishReq) ProtoReflect() protoreflect.Message {
	mi := &file_msdbcall_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDishReq.ProtoReflect.Descriptor instead.
func (*DeleteDishReq) Descriptor() ([]byte, []int) {
	return file_msdbcall_proto_rawDescGZIP(), []int{16}
}

func (x *DeleteDishReq) GetId() int32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

type DeleteDishResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status *int32 `protobuf:"varint,1,opt,name=status" json:"status,omitempty"`
}

func (x *DeleteDishResp) Reset() {
	*x = DeleteDishResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msdbcall_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteDishResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDishResp) ProtoMessage() {}

func (x *DeleteDishResp) ProtoReflect() protoreflect.Message {
	mi := &file_msdbcall_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDishResp.ProtoReflect.Descriptor instead.
func (*DeleteDishResp) Descriptor() ([]byte, []int) {
	return file_msdbcall_proto_rawDescGZIP(), []int{17}
}

func (x *DeleteDishResp) GetStatus() int32 {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return 0
}

type GetDishInfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DishId *int32 `protobuf:"varint,1,opt,name=dish_id,json=dishId" json:"dish_id,omitempty"`
}

func (x *GetDishInfoReq) Reset() {
	*x = GetDishInfoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msdbcall_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDishInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDishInfoReq) ProtoMessage() {}

func (x *GetDishInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_msdbcall_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDishInfoReq.ProtoReflect.Descriptor instead.
func (*GetDishInfoReq) Descriptor() ([]byte, []int) {
	return file_msdbcall_proto_rawDescGZIP(), []int{18}
}

func (x *GetDishInfoReq) GetDishId() int32 {
	if x != nil && x.DishId != nil {
		return *x.DishId
	}
	return 0
}

type GetDishInfoResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status *int32      `protobuf:"varint,1,opt,name=status" json:"status,omitempty"`
	Dish   *proto.Dish `protobuf:"bytes,2,opt,name=dish" json:"dish,omitempty"`
}

func (x *GetDishInfoResp) Reset() {
	*x = GetDishInfoResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msdbcall_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDishInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDishInfoResp) ProtoMessage() {}

func (x *GetDishInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_msdbcall_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDishInfoResp.ProtoReflect.Descriptor instead.
func (*GetDishInfoResp) Descriptor() ([]byte, []int) {
	return file_msdbcall_proto_rawDescGZIP(), []int{19}
}

func (x *GetDishInfoResp) GetStatus() int32 {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return 0
}

func (x *GetDishInfoResp) GetDish() *proto.Dish {
	if x != nil {
		return x.Dish
	}
	return nil
}

type GetUserDiscountReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uin *string `protobuf:"bytes,1,opt,name=uin" json:"uin,omitempty"`
}

func (x *GetUserDiscountReq) Reset() {
	*x = GetUserDiscountReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msdbcall_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserDiscountReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserDiscountReq) ProtoMessage() {}

func (x *GetUserDiscountReq) ProtoReflect() protoreflect.Message {
	mi := &file_msdbcall_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserDiscountReq.ProtoReflect.Descriptor instead.
func (*GetUserDiscountReq) Descriptor() ([]byte, []int) {
	return file_msdbcall_proto_rawDescGZIP(), []int{20}
}

func (x *GetUserDiscountReq) GetUin() string {
	if x != nil && x.Uin != nil {
		return *x.Uin
	}
	return ""
}

type GetUserDiscountResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status   *int32   `protobuf:"varint,1,opt,name=status" json:"status,omitempty"`
	Discount *float64 `protobuf:"fixed64,2,opt,name=discount" json:"discount,omitempty"`
}

func (x *GetUserDiscountResp) Reset() {
	*x = GetUserDiscountResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msdbcall_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserDiscountResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserDiscountResp) ProtoMessage() {}

func (x *GetUserDiscountResp) ProtoReflect() protoreflect.Message {
	mi := &file_msdbcall_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserDiscountResp.ProtoReflect.Descriptor instead.
func (*GetUserDiscountResp) Descriptor() ([]byte, []int) {
	return file_msdbcall_proto_rawDescGZIP(), []int{21}
}

func (x *GetUserDiscountResp) GetStatus() int32 {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return 0
}

func (x *GetUserDiscountResp) GetDiscount() float64 {
	if x != nil && x.Discount != nil {
		return *x.Discount
	}
	return 0
}

type StoreConsumeRecordReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *string `protobuf:"bytes,1,opt,name=data" json:"data,omitempty"`
}

func (x *StoreConsumeRecordReq) Reset() {
	*x = StoreConsumeRecordReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msdbcall_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StoreConsumeRecordReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreConsumeRecordReq) ProtoMessage() {}

func (x *StoreConsumeRecordReq) ProtoReflect() protoreflect.Message {
	mi := &file_msdbcall_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreConsumeRecordReq.ProtoReflect.Descriptor instead.
func (*StoreConsumeRecordReq) Descriptor() ([]byte, []int) {
	return file_msdbcall_proto_rawDescGZIP(), []int{22}
}

func (x *StoreConsumeRecordReq) GetData() string {
	if x != nil && x.Data != nil {
		return *x.Data
	}
	return ""
}

type StoreConsumeRecordResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status *int32 `protobuf:"varint,1,opt,name=status" json:"status,omitempty"`
}

func (x *StoreConsumeRecordResp) Reset() {
	*x = StoreConsumeRecordResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msdbcall_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StoreConsumeRecordResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreConsumeRecordResp) ProtoMessage() {}

func (x *StoreConsumeRecordResp) ProtoReflect() protoreflect.Message {
	mi := &file_msdbcall_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreConsumeRecordResp.ProtoReflect.Descriptor instead.
func (*StoreConsumeRecordResp) Descriptor() ([]byte, []int) {
	return file_msdbcall_proto_rawDescGZIP(), []int{23}
}

func (x *StoreConsumeRecordResp) GetStatus() int32 {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return 0
}

type GetConsumeRecordReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Start *uint32 `protobuf:"varint,1,opt,name=start" json:"start,omitempty"`
	End   *uint32 `protobuf:"varint,2,opt,name=end" json:"end,omitempty"`
}

func (x *GetConsumeRecordReq) Reset() {
	*x = GetConsumeRecordReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msdbcall_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetConsumeRecordReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConsumeRecordReq) ProtoMessage() {}

func (x *GetConsumeRecordReq) ProtoReflect() protoreflect.Message {
	mi := &file_msdbcall_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConsumeRecordReq.ProtoReflect.Descriptor instead.
func (*GetConsumeRecordReq) Descriptor() ([]byte, []int) {
	return file_msdbcall_proto_rawDescGZIP(), []int{24}
}

func (x *GetConsumeRecordReq) GetStart() uint32 {
	if x != nil && x.Start != nil {
		return *x.Start
	}
	return 0
}

func (x *GetConsumeRecordReq) GetEnd() uint32 {
	if x != nil && x.End != nil {
		return *x.End
	}
	return 0
}

type GetConsumeRecordResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status *int32   `protobuf:"varint,1,opt,name=status" json:"status,omitempty"`
	Data   []string `protobuf:"bytes,2,rep,name=data" json:"data,omitempty"`
}

func (x *GetConsumeRecordResp) Reset() {
	*x = GetConsumeRecordResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msdbcall_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetConsumeRecordResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConsumeRecordResp) ProtoMessage() {}

func (x *GetConsumeRecordResp) ProtoReflect() protoreflect.Message {
	mi := &file_msdbcall_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConsumeRecordResp.ProtoReflect.Descriptor instead.
func (*GetConsumeRecordResp) Descriptor() ([]byte, []int) {
	return file_msdbcall_proto_rawDescGZIP(), []int{25}
}

func (x *GetConsumeRecordResp) GetStatus() int32 {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return 0
}

func (x *GetConsumeRecordResp) GetData() []string {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_msdbcall_proto protoreflect.FileDescriptor

var file_msdbcall_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x6d, 0x73, 0x64, 0x62, 0x63, 0x61, 0x6c, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x6d, 0x73, 0x64, 0x62, 0x63, 0x61, 0x6c, 0x6c, 0x1a, 0x11, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x30, 0x0a,
	0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x1f,
	0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x6d,
	0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x22,
	0x38, 0x0a, 0x0e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x22, 0x2d, 0x0a, 0x0a, 0x41, 0x64, 0x64,
	0x44, 0x69, 0x73, 0x68, 0x52, 0x65, 0x71, 0x12, 0x1f, 0x0a, 0x04, 0x64, 0x69, 0x73, 0x68, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x44, 0x69,
	0x73, 0x68, 0x52, 0x04, 0x64, 0x69, 0x73, 0x68, 0x22, 0x21, 0x0a, 0x0b, 0x41, 0x64, 0x64, 0x44,
	0x69, 0x73, 0x68, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x7d, 0x0a, 0x14, 0x43,
	0x68, 0x65, 0x63, 0x6b, 0x55, 0x73, 0x65, 0x72, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64,
	0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x75, 0x69, 0x6e, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x5f, 0x6e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x68, 0x6f,
	0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69,
	0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x1a,
	0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x2f, 0x0a, 0x15, 0x43, 0x68,
	0x65, 0x63, 0x6b, 0x55, 0x73, 0x65, 0x72, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x5b, 0x0a, 0x0e, 0x47,
	0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a,
	0x03, 0x75, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x6e, 0x12,
	0x21, 0x0a, 0x0c, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x22, 0x3d, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0xa4, 0x01, 0x0a, 0x11, 0x4d, 0x6f, 0x64, 0x69,
	0x66, 0x79, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a,
	0x03, 0x75, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x6e, 0x12,
	0x21, 0x0a, 0x0c, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x21, 0x0a, 0x0c, 0x6f, 0x6c, 0x64, 0x5f,
	0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x6f, 0x6c, 0x64, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x6e,
	0x65, 0x77, 0x5f, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x6e, 0x65, 0x77, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x2c,
	0x0a, 0x12, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x3c, 0x0a, 0x17,
	0x43, 0x68, 0x65, 0x63, 0x6b, 0x55, 0x73, 0x65, 0x72, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x55, 0x6e,
	0x69, 0x71, 0x75, 0x65, 0x52, 0x65, 0x71, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x68, 0x6f, 0x6e, 0x65,
	0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70,
	0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x32, 0x0a, 0x18, 0x43, 0x68,
	0x65, 0x63, 0x6b, 0x55, 0x73, 0x65, 0x72, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x55, 0x6e, 0x69, 0x71,
	0x75, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x6e, 0x69, 0x71, 0x75, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x75, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x22, 0x2f,
	0x0a, 0x17, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x55, 0x73, 0x65, 0x72, 0x45, 0x6d, 0x61, 0x69, 0x6c,
	0x55, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61,
	0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x22,
	0x32, 0x0a, 0x18, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x55, 0x73, 0x65, 0x72, 0x45, 0x6d, 0x61, 0x69,
	0x6c, 0x55, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x75,
	0x6e, 0x69, 0x71, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x75, 0x6e, 0x69,
	0x71, 0x75, 0x65, 0x22, 0x10, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x44, 0x69, 0x73, 0x68, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x71, 0x22, 0x3b, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x44, 0x69, 0x73, 0x68,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x28, 0x0a, 0x09, 0x64, 0x69, 0x73, 0x68,
	0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x2e, 0x44, 0x69, 0x73, 0x68, 0x52, 0x08, 0x64, 0x69, 0x73, 0x68, 0x4c, 0x69,
	0x73, 0x74, 0x22, 0x1f, 0x0a, 0x0d, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x44, 0x69, 0x73, 0x68,
	0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x02, 0x69, 0x64, 0x22, 0x28, 0x0a, 0x0e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x44, 0x69, 0x73,
	0x68, 0x52, 0x65, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x29, 0x0a,
	0x0e, 0x47, 0x65, 0x74, 0x44, 0x69, 0x73, 0x68, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x12,
	0x17, 0x0a, 0x07, 0x64, 0x69, 0x73, 0x68, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x64, 0x69, 0x73, 0x68, 0x49, 0x64, 0x22, 0x4a, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x44,
	0x69, 0x73, 0x68, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x1f, 0x0a, 0x04, 0x64, 0x69, 0x73, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0b, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x44, 0x69, 0x73, 0x68, 0x52, 0x04,
	0x64, 0x69, 0x73, 0x68, 0x22, 0x26, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x44,
	0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x6e, 0x22, 0x49, 0x0a, 0x13,
	0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x64,
	0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x64,
	0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x2b, 0x0a, 0x15, 0x53, 0x74, 0x6f, 0x72, 0x65,
	0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71,
	0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x22, 0x30, 0x0a, 0x16, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x43, 0x6f, 0x6e,
	0x73, 0x75, 0x6d, 0x65, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x3d, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e,
	0x73, 0x75, 0x6d, 0x65, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a,
	0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x73, 0x74,
	0x61, 0x72, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x03, 0x65, 0x6e, 0x64, 0x22, 0x42, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x73,
	0x75, 0x6d, 0x65, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x12, 0x16, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x32, 0xed, 0x07, 0x0a, 0x08, 0x4d, 0x53,
	0x44, 0x42, 0x43, 0x61, 0x6c, 0x6c, 0x12, 0x3f, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x55, 0x73, 0x65, 0x72, 0x12, 0x17, 0x2e, 0x6d, 0x73, 0x64, 0x62, 0x63, 0x61, 0x6c, 0x6c, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x18, 0x2e,
	0x6d, 0x73, 0x64, 0x62, 0x63, 0x61, 0x6c, 0x6c, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55,
	0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x36, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x44, 0x69,
	0x73, 0x68, 0x12, 0x14, 0x2e, 0x6d, 0x73, 0x64, 0x62, 0x63, 0x61, 0x6c, 0x6c, 0x2e, 0x41, 0x64,
	0x64, 0x44, 0x69, 0x73, 0x68, 0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e, 0x6d, 0x73, 0x64, 0x62, 0x63,
	0x61, 0x6c, 0x6c, 0x2e, 0x41, 0x64, 0x64, 0x44, 0x69, 0x73, 0x68, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x54, 0x0a, 0x11, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x55, 0x73, 0x65, 0x72, 0x50, 0x61, 0x73, 0x73,
	0x77, 0x6f, 0x72, 0x64, 0x12, 0x1e, 0x2e, 0x6d, 0x73, 0x64, 0x62, 0x63, 0x61, 0x6c, 0x6c, 0x2e,
	0x43, 0x68, 0x65, 0x63, 0x6b, 0x55, 0x73, 0x65, 0x72, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72,
	0x64, 0x52, 0x65, 0x71, 0x1a, 0x1f, 0x2e, 0x6d, 0x73, 0x64, 0x62, 0x63, 0x61, 0x6c, 0x6c, 0x2e,
	0x43, 0x68, 0x65, 0x63, 0x6b, 0x55, 0x73, 0x65, 0x72, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72,
	0x64, 0x52, 0x65, 0x73, 0x70, 0x12, 0x4b, 0x0a, 0x0e, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x50,
	0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x1b, 0x2e, 0x6d, 0x73, 0x64, 0x62, 0x63, 0x61,
	0x6c, 0x6c, 0x2e, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72,
	0x64, 0x52, 0x65, 0x71, 0x1a, 0x1c, 0x2e, 0x6d, 0x73, 0x64, 0x62, 0x63, 0x61, 0x6c, 0x6c, 0x2e,
	0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x5d, 0x0a, 0x14, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x55, 0x73, 0x65, 0x72, 0x50,
	0x68, 0x6f, 0x6e, 0x65, 0x55, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x12, 0x21, 0x2e, 0x6d, 0x73, 0x64,
	0x62, 0x63, 0x61, 0x6c, 0x6c, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x55, 0x73, 0x65, 0x72, 0x50,
	0x68, 0x6f, 0x6e, 0x65, 0x55, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x22, 0x2e,
	0x6d, 0x73, 0x64, 0x62, 0x63, 0x61, 0x6c, 0x6c, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x55, 0x73,
	0x65, 0x72, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x55, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x5d, 0x0a, 0x14, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x55, 0x73, 0x65, 0x72, 0x45, 0x6d,
	0x61, 0x69, 0x6c, 0x55, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x12, 0x21, 0x2e, 0x6d, 0x73, 0x64, 0x62,
	0x63, 0x61, 0x6c, 0x6c, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x55, 0x73, 0x65, 0x72, 0x45, 0x6d,
	0x61, 0x69, 0x6c, 0x55, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x22, 0x2e, 0x6d,
	0x73, 0x64, 0x62, 0x63, 0x61, 0x6c, 0x6c, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x55, 0x73, 0x65,
	0x72, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x55, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x42, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x18, 0x2e, 0x6d, 0x73, 0x64, 0x62, 0x63, 0x61, 0x6c, 0x6c, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x1a, 0x19, 0x2e, 0x6d, 0x73, 0x64, 0x62,
	0x63, 0x61, 0x6c, 0x6c, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x42, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x44, 0x69, 0x73, 0x68, 0x4c,
	0x69, 0x73, 0x74, 0x12, 0x18, 0x2e, 0x6d, 0x73, 0x64, 0x62, 0x63, 0x61, 0x6c, 0x6c, 0x2e, 0x47,
	0x65, 0x74, 0x44, 0x69, 0x73, 0x68, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x19, 0x2e,
	0x6d, 0x73, 0x64, 0x62, 0x63, 0x61, 0x6c, 0x6c, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x69, 0x73, 0x68,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x3f, 0x0a, 0x0a, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x44, 0x69, 0x73, 0x68, 0x12, 0x17, 0x2e, 0x6d, 0x73, 0x64, 0x62, 0x63, 0x61, 0x6c,
	0x6c, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x44, 0x69, 0x73, 0x68, 0x52, 0x65, 0x71, 0x1a,
	0x18, 0x2e, 0x6d, 0x73, 0x64, 0x62, 0x63, 0x61, 0x6c, 0x6c, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x44, 0x69, 0x73, 0x68, 0x52, 0x65, 0x73, 0x70, 0x12, 0x42, 0x0a, 0x0b, 0x47, 0x65, 0x74,
	0x44, 0x69, 0x73, 0x68, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x18, 0x2e, 0x6d, 0x73, 0x64, 0x62, 0x63,
	0x61, 0x6c, 0x6c, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x69, 0x73, 0x68, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x65, 0x71, 0x1a, 0x19, 0x2e, 0x6d, 0x73, 0x64, 0x62, 0x63, 0x61, 0x6c, 0x6c, 0x2e, 0x47, 0x65,
	0x74, 0x44, 0x69, 0x73, 0x68, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x12, 0x4e, 0x0a,
	0x0f, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x12, 0x1c, 0x2e, 0x6d, 0x73, 0x64, 0x62, 0x63, 0x61, 0x6c, 0x6c, 0x2e, 0x47, 0x65, 0x74, 0x55,
	0x73, 0x65, 0x72, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x1d,
	0x2e, 0x6d, 0x73, 0x64, 0x62, 0x63, 0x61, 0x6c, 0x6c, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65,
	0x72, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x57, 0x0a,
	0x12, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x52, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x12, 0x1f, 0x2e, 0x6d, 0x73, 0x64, 0x62, 0x63, 0x61, 0x6c, 0x6c, 0x2e, 0x53,
	0x74, 0x6f, 0x72, 0x65, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x52, 0x65, 0x63, 0x6f, 0x72,
	0x64, 0x52, 0x65, 0x71, 0x1a, 0x20, 0x2e, 0x6d, 0x73, 0x64, 0x62, 0x63, 0x61, 0x6c, 0x6c, 0x2e,
	0x53, 0x74, 0x6f, 0x72, 0x65, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x52, 0x65, 0x63, 0x6f,
	0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x12, 0x51, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e,
	0x73, 0x75, 0x6d, 0x65, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x1d, 0x2e, 0x6d, 0x73, 0x64,
	0x62, 0x63, 0x61, 0x6c, 0x6c, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65,
	0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x1e, 0x2e, 0x6d, 0x73, 0x64, 0x62,
	0x63, 0x61, 0x6c, 0x6c, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x52,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x3b, 0x6d,
	0x73, 0x64, 0x62, 0x63, 0x61, 0x6c, 0x6c,
}

var (
	file_msdbcall_proto_rawDescOnce sync.Once
	file_msdbcall_proto_rawDescData = file_msdbcall_proto_rawDesc
)

func file_msdbcall_proto_rawDescGZIP() []byte {
	file_msdbcall_proto_rawDescOnce.Do(func() {
		file_msdbcall_proto_rawDescData = protoimpl.X.CompressGZIP(file_msdbcall_proto_rawDescData)
	})
	return file_msdbcall_proto_rawDescData
}

var file_msdbcall_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_msdbcall_proto_goTypes = []interface{}{
	(*CreateUserReq)(nil),            // 0: msdbcall.CreateUserReq
	(*CreateUserResp)(nil),           // 1: msdbcall.CreateUserResp
	(*AddDishReq)(nil),               // 2: msdbcall.AddDishReq
	(*AddDishResp)(nil),              // 3: msdbcall.AddDishResp
	(*CheckUserPasswordReq)(nil),     // 4: msdbcall.CheckUserPasswordReq
	(*CheckUserPasswordResp)(nil),    // 5: msdbcall.CheckUserPasswordResp
	(*GetUserInfoReq)(nil),           // 6: msdbcall.GetUserInfoReq
	(*GetUserInfoResp)(nil),          // 7: msdbcall.GetUserInfoResp
	(*ModifyPasswordReq)(nil),        // 8: msdbcall.ModifyPasswordReq
	(*ModifyPasswordResp)(nil),       // 9: msdbcall.ModifyPasswordResp
	(*CheckUserPhoneUniqueReq)(nil),  // 10: msdbcall.CheckUserPhoneUniqueReq
	(*CheckUserPhoneUniqueResp)(nil), // 11: msdbcall.CheckUserPhoneUniqueResp
	(*CheckUserEmailUniqueReq)(nil),  // 12: msdbcall.CheckUserEmailUniqueReq
	(*CheckUserEmailUniqueResp)(nil), // 13: msdbcall.CheckUserEmailUniqueResp
	(*GetDishListReq)(nil),           // 14: msdbcall.GetDishListReq
	(*GetDishListResp)(nil),          // 15: msdbcall.GetDishListResp
	(*DeleteDishReq)(nil),            // 16: msdbcall.DeleteDishReq
	(*DeleteDishResp)(nil),           // 17: msdbcall.DeleteDishResp
	(*GetDishInfoReq)(nil),           // 18: msdbcall.GetDishInfoReq
	(*GetDishInfoResp)(nil),          // 19: msdbcall.GetDishInfoResp
	(*GetUserDiscountReq)(nil),       // 20: msdbcall.GetUserDiscountReq
	(*GetUserDiscountResp)(nil),      // 21: msdbcall.GetUserDiscountResp
	(*StoreConsumeRecordReq)(nil),    // 22: msdbcall.StoreConsumeRecordReq
	(*StoreConsumeRecordResp)(nil),   // 23: msdbcall.StoreConsumeRecordResp
	(*GetConsumeRecordReq)(nil),      // 24: msdbcall.GetConsumeRecordReq
	(*GetConsumeRecordResp)(nil),     // 25: msdbcall.GetConsumeRecordResp
	(*proto.User)(nil),               // 26: model.User
	(*proto.Dish)(nil),               // 27: model.Dish
}
var file_msdbcall_proto_depIdxs = []int32{
	26, // 0: msdbcall.CreateUserReq.user:type_name -> model.User
	27, // 1: msdbcall.AddDishReq.dish:type_name -> model.Dish
	27, // 2: msdbcall.GetDishListResp.dish_list:type_name -> model.Dish
	27, // 3: msdbcall.GetDishInfoResp.dish:type_name -> model.Dish
	0,  // 4: msdbcall.MSDBCall.CreateUser:input_type -> msdbcall.CreateUserReq
	2,  // 5: msdbcall.MSDBCall.AddDish:input_type -> msdbcall.AddDishReq
	4,  // 6: msdbcall.MSDBCall.CheckUserPassword:input_type -> msdbcall.CheckUserPasswordReq
	8,  // 7: msdbcall.MSDBCall.ModifyPassword:input_type -> msdbcall.ModifyPasswordReq
	10, // 8: msdbcall.MSDBCall.CheckUserPhoneUnique:input_type -> msdbcall.CheckUserPhoneUniqueReq
	12, // 9: msdbcall.MSDBCall.CheckUserEmailUnique:input_type -> msdbcall.CheckUserEmailUniqueReq
	6,  // 10: msdbcall.MSDBCall.GetUserInfo:input_type -> msdbcall.GetUserInfoReq
	14, // 11: msdbcall.MSDBCall.GetDishList:input_type -> msdbcall.GetDishListReq
	16, // 12: msdbcall.MSDBCall.DeleteDish:input_type -> msdbcall.DeleteDishReq
	18, // 13: msdbcall.MSDBCall.GetDishInfo:input_type -> msdbcall.GetDishInfoReq
	20, // 14: msdbcall.MSDBCall.GetUserDiscount:input_type -> msdbcall.GetUserDiscountReq
	22, // 15: msdbcall.MSDBCall.StoreConsumeRecord:input_type -> msdbcall.StoreConsumeRecordReq
	24, // 16: msdbcall.MSDBCall.GetConsumeRecord:input_type -> msdbcall.GetConsumeRecordReq
	1,  // 17: msdbcall.MSDBCall.CreateUser:output_type -> msdbcall.CreateUserResp
	3,  // 18: msdbcall.MSDBCall.AddDish:output_type -> msdbcall.AddDishResp
	5,  // 19: msdbcall.MSDBCall.CheckUserPassword:output_type -> msdbcall.CheckUserPasswordResp
	9,  // 20: msdbcall.MSDBCall.ModifyPassword:output_type -> msdbcall.ModifyPasswordResp
	11, // 21: msdbcall.MSDBCall.CheckUserPhoneUnique:output_type -> msdbcall.CheckUserPhoneUniqueResp
	13, // 22: msdbcall.MSDBCall.CheckUserEmailUnique:output_type -> msdbcall.CheckUserEmailUniqueResp
	7,  // 23: msdbcall.MSDBCall.GetUserInfo:output_type -> msdbcall.GetUserInfoResp
	15, // 24: msdbcall.MSDBCall.GetDishList:output_type -> msdbcall.GetDishListResp
	17, // 25: msdbcall.MSDBCall.DeleteDish:output_type -> msdbcall.DeleteDishResp
	19, // 26: msdbcall.MSDBCall.GetDishInfo:output_type -> msdbcall.GetDishInfoResp
	21, // 27: msdbcall.MSDBCall.GetUserDiscount:output_type -> msdbcall.GetUserDiscountResp
	23, // 28: msdbcall.MSDBCall.StoreConsumeRecord:output_type -> msdbcall.StoreConsumeRecordResp
	25, // 29: msdbcall.MSDBCall.GetConsumeRecord:output_type -> msdbcall.GetConsumeRecordResp
	17, // [17:30] is the sub-list for method output_type
	4,  // [4:17] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_msdbcall_proto_init() }
func file_msdbcall_proto_init() {
	if File_msdbcall_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_msdbcall_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateUserReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msdbcall_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateUserResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msdbcall_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddDishReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msdbcall_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddDishResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msdbcall_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckUserPasswordReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msdbcall_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckUserPasswordResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msdbcall_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserInfoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msdbcall_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserInfoResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msdbcall_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModifyPasswordReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msdbcall_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModifyPasswordResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msdbcall_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckUserPhoneUniqueReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msdbcall_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckUserPhoneUniqueResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msdbcall_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckUserEmailUniqueReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msdbcall_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckUserEmailUniqueResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msdbcall_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDishListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msdbcall_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDishListResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msdbcall_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteDishReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msdbcall_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteDishResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msdbcall_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDishInfoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msdbcall_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDishInfoResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msdbcall_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserDiscountReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msdbcall_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserDiscountResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msdbcall_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StoreConsumeRecordReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msdbcall_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StoreConsumeRecordResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msdbcall_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetConsumeRecordReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msdbcall_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetConsumeRecordResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_msdbcall_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_msdbcall_proto_goTypes,
		DependencyIndexes: file_msdbcall_proto_depIdxs,
		MessageInfos:      file_msdbcall_proto_msgTypes,
	}.Build()
	File_msdbcall_proto = out.File
	file_msdbcall_proto_rawDesc = nil
	file_msdbcall_proto_goTypes = nil
	file_msdbcall_proto_depIdxs = nil
}
