info:
  contact: {}
paths:
  /add-table:
    get:
      description: '"加台"'
      parameters:
      - description: table_id
        in: formData
        name: table_id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: json
      summary: AddTable
      tags:
      - public
  /admin/add-dish:
    get:
      description: '"添加一道菜"'
      parameters:
      - description: name
        in: query
        name: name
        required: true
        type: string
      - description: price
        in: query
        name: price
        required: true
        type: number
      - description: discount
        in: query
        name: discount
        required: true
        type: number
      - description: detail
        in: query
        name: detail
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: json
      summary: AddDish
      tags:
      - public
  /admin/complete-table:
    get:
      description: '"结台"'
      parameters:
      - description: table_id
        in: query
        name: table_id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: json
      summary: CompleteTable
      tags:
      - public
  /admin/open-table:
    get:
      description: '"开台"'
      parameters:
      - description: table_id
        in: query
        name: table_id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: json
      summary: OpenTable
      tags:
      - public
  /del-table:
    get:
      description: '"加台"'
      parameters:
      - description: table_id
        in: formData
        name: table_id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: json
      summary: DelTable
      tags:
      - public
  /get-tables-status:
    get:
      description: '"获得桌台详情"'
      responses:
        "200":
          description: OK
          schema:
            type: json
      summary: GetTablesStatus
      tags:
      - public
  /login-by-name:
    post:
      description: '"登录"'
      parameters:
      - description: 用户名
        in: formData
        name: name
        required: true
        type: string
      - description: MD5加密密码
        in: formData
        name: password
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: json
      summary: LoginByName
      tags:
      - public
  /login-by-token:
    post:
      description: '"登录"'
      parameters:
      - description: token
        in: formData
        name: token
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: json
      summary: LoginByJWT
      tags:
      - public
  /ping:
    get:
      description: '"ping一下服务器"'
      parameters:
      - description: 回复
        in: query
        name: message
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: json
      summary: ping
      tags:
      - example
  /register:
    post:
      description: '"注册新用户"'
      parameters:
      - description: 用户名
        in: formData
        name: name
        required: true
        type: string
      - description: MD5加密密码
        in: formData
        name: password
        required: true
        type: string
      - description: 手机
        in: formData
        name: phone_number
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: json
      summary: Register
      tags:
      - public
swagger: "2.0"
