info:
  contact: {}
paths:
  /admin/add-dish:
    get:
      description: '"添加一道菜"'
      parameters:
      - description: name
        in: query
        name: name
        required: true
        type: string
      - description: price
        in: query
        name: price
        required: true
        type: number
      - description: discount
        in: query
        name: discount
        required: true
        type: number
      - description: detail
        in: query
        name: detail
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: json
      summary: AddDish
      tags:
      - public
  /admin/add-table:
    get:
      description: '"加台"'
      parameters:
      - description: table_id
        in: formData
        name: table_id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: json
      summary: AddTable
      tags:
      - public
  /admin/complete-table:
    get:
      description: '"结台"'
      parameters:
      - description: table_id
        in: query
        name: table_id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: json
      summary: CompleteTable
      tags:
      - public
  /admin/del-table:
    get:
      description: '"减台"'
      parameters:
      - description: table_id
        in: query
        name: table_id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: json
      summary: DelTable
      tags:
      - public
  /admin/delete-dish:
    get:
      description: '"删除一道菜，如果dish_id不存在，不会返回失败"'
      parameters:
      - description: dish_id
        in: query
        name: dish_id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: json
      summary: DeleteDish
      tags:
      - public
  /admin/open-table:
    get:
      description: '"开台"'
      parameters:
      - description: table_id
        in: query
        name: table_id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: json
      summary: OpenTable
      tags:
      - public
  /check-user-password:
    get:
      description: '"检查md5加密用户密码是否正确"'
      parameters:
      - description: uin
        in: query
        name: uin
        type: string
      - description: phone_number
        in: query
        name: phone_number
        type: string
      - description: email
        in: query
        name: email
        type: string
      - description: password
        in: formData
        name: password
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: json
      summary: CallCheckUserPassword
      tags:
      - public
  /get-dish-info:
    get:
      description: '"获得菜品详情"'
      parameters:
      - description: dish_id
        in: query
        name: dish_id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: json
      summary: GetDishInfo
      tags:
      - public
  /get-dish-list:
    get:
      description: '"获取菜品列表"'
      responses:
        "200":
          description: OK
          schema:
            type: json
      summary: GetDishList
      tags:
      - public
  /get-table-info:
    get:
      description: '"获取桌台详情，包括桌台状态、点菜等"'
      parameters:
      - description: 桌台id
        in: query
        name: table_id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: json
      summary: GetTableInfo
      tags:
      - public
  /get-tables-status:
    get:
      description: '"获得全部桌台状态"'
      responses:
        "200":
          description: OK
          schema:
            type: json
      summary: GetTablesStatus
      tags:
      - public
  /login:
    post:
      description: '"登录"'
      parameters:
      - description: 手机号
        in: query
        name: phone_number
        required: true
        type: string
      - description: MD5加密密码
        in: formData
        name: password
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: json
      summary: Login
      tags:
      - public
  /login-by-token:
    post:
      description: '"登录"'
      parameters:
      - description: token
        in: formData
        name: token
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: json
      summary: LoginByJWT
      tags:
      - public
  /modify-password:
    post:
      description: '"修改密码"'
      parameters:
      - description: uin
        in: query
        name: uin
        type: string
      - description: phone_numer
        in: query
        name: phone_number
        type: string
      - description: email
        in: query
        name: email
        type: string
      - description: old_password
        in: formData
        name: old_password
        required: true
        type: string
      - description: new_password
        in: formData
        name: new_password
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: json
      summary: ModifyPassword
      tags:
      - public
  /order-dish:
    post:
      description: '"点菜"'
      parameters:
      - description: table_id
        in: query
        name: table_id
        required: true
        type: string
      - collectionFormat: csv
        description: dish_id
        in: formData
        items:
          type: string
        name: dish_id
        required: true
        type: array
      responses:
        "200":
          description: OK
          schema:
            type: json
      summary: OrderDish
      tags:
      - public
  /ping:
    get:
      description: '"ping一下服务器"'
      parameters:
      - description: 回复
        in: query
        name: message
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: json
      summary: ping
      tags:
      - example
  /register:
    post:
      description: '"注册新用户"'
      parameters:
      - description: 用户名
        in: formData
        name: name
        required: true
        type: string
      - description: MD5加密密码
        in: formData
        name: password
        required: true
        type: string
      - description: 手机
        in: formData
        name: phone_number
        required: true
        type: string
      - description: 邮箱
        in: formData
        name: email
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: json
      summary: Register
      tags:
      - public
swagger: "2.0"
